### ISSUE TITLE
Replace the Server

### ISSUE THREAD

**Issue by hanyuzzw** [ARMmbed/mbed-cloud-client-example#34]
Hello!  
I want to ask if I replace the lwm2m server to others(like [Leshan](https://leshan.eclipse.org/#/clients) or local server),does the client still work? and how to solve the Security credentials problem?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3251

**Comment by hanyuzzw** [comment]
> ARM Internal Ref: IOTCLT-3251

But how to access it ？

**Comment by JanneKiiskila** [comment]
Hi,

We are not testing nor guaranteeing any compatibility with other LwM2M servers (such as Leshan). The Pelion Device Management Client works against Pelion Device Management solution. I.e. non-supported feature and we are not planning to support generic LwM2M servers either (at least for now).
