### ISSUE TITLE
EAPOL Key Message 4 of 4 twice

### ISSUE THREAD

**Issue by dannywahlquist** [ARMmbed/mbed-cloud-client-example#58]
Any idea why my devices respond to EAPOL Key Message 1 of 4 and 3 of 4 with 4 of 4 both times?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3901

**Comment by yogpan01** [comment]
Hi,
Can you please elaborate your use case? 
What is EAPOL Key Message and what is the sequence you are expecting vs. what you are observing?

**Comment by dannywahlquist** [comment]
I verified that it is working correctly. The Wireshark dissector is reporting message 2 as 4 because of the way WiSUN modifies the 4-way handshake.

**Comment by yogpan01** [comment]
Good to know that its working fine. Can this be considered as resolved and issue can be closed?

**Comment by dannywahlquist** [comment]
Yes, thanks!
