### ISSUE TITLE
What combinations of wisun domain, class, and mode are supported?

### ISSUE THREAD

**Issue by dannywahlquist** [ARMmbed/mbed-cloud-client-example#59]
I was particularly trying to run PHxA class 2, mode 3 to have only 7 channels.

            "mbed-mesh-api.wisun-regulatory-domain"     : "10",
            "mbed-mesh-api.wisun-operating-class"       : "2",
            "mbed-mesh-api.wisun-operating-mode"        : "3",

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3909

**Comment by yogpan01** [comment]
@mikter Can you please provide details for these configurations?

**Comment by dannywahlquist** [comment]
WiSUN Philippines domain 0X0A, class 2, mode 3 supports Channel Spacing (400kHz), Total Number of Channels 7, Channel Center Freq0 (915.4 MHz).

**Comment by mikter** [comment]
We currently only support EU, North America, Korea regulatory domains. as we have not included the conversion table for all regulatory domains, modes and class from the Wi-SUN PHY specification.

If you must use the Philippines Regulatory domain it can be added in this file 
https://github.com/ARMmbed/mbed-os/blob/master/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
to ws_common_regulatory_domain_config() function.

**Comment by dannywahlquist** [comment]
Worked perfectly, thanks!
